package visitor

// visitResponse to handle uniform response for every method/rule of the MonkeyParserVisitor
type visitResponse struct {
	node   map[string]interface{}
	failed bool
}

// hasFailed an error occured within the rule
func (r *visitResponse) hasFailed() bool {
	return r.failed
}

// info generated by every rule (parent and children nodes)
func (r *visitResponse) info() map[string]interface{} {
	return r.node
}
